name: CI 

on:
  push:
    branches:
      - main
      - develop
    tags: 'REL-*'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: ["Debug", "Release"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build projects
        run: BUILD_CONFIG=${{ matrix.config }} make docker
      - name: Release
        uses: ncipollo/release-action@v1
        if: >-
          github.event_name == 'push' &&
          startsWith(github.event.ref, 'refs/tags')
        with:
          generateReleaseNotes: true
          token: ${{ secrets.RELEASE_TOKEN }}
